### ISSUE TITLE
Make sure you can build the project with picamera on non-raspi machines

### ISSUE THREAD

**Issue by kir486680** [kir486680/Open-Science-Bot#8]
When you try to install picamera on a machine which is not raspi, you get "raise ValueError('Unable to determine if this system is a Raspberry Pi')" We gotta allow people build project without this.

**Comment by jaegpark** [comment]
this is a good issue, will work on it today

**Comment by jaegpark** [comment]
#9

**Comment by jaegpark** [comment]
Fixed with #9
